# Generated by Django 4.2.7 on 2024-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='visit',
            field=models.CharField(choices=[('первичный прием', 'первичный прием'), ('повторный прием', 'повторный прием')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
